### ISSUE TITLE
Incomplete function in Clause.cc

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#207]
https://github.com/sfc-aqua/quisp/blob/f9db91abded6ff78e5e9160c342a0c41fd728404/quisp/rules/Clause.cc#L24

https://github.com/sfc-aqua/quisp/blob/f9db91abded6ff78e5e9160c342a0c41fd728404/quisp/rules/Clause.cc#L160

These functions here doesn't return anything even though it has `bool` signature. So either delete it or fix it if some code uses this currently

**Comment by Chibikuri** [comment]
Fixed in the latest master. 
https://github.com/sfc-aqua/quisp/blob/5ad49f9d3afb66a9919d9e1f5c4ffe62136f4bf8/quisp/rules/clauses/FidelityClause.cc#L9
This one lefts error throw though. 
https://github.com/sfc-aqua/quisp/blob/5ad49f9d3afb66a9919d9e1f5c4ffe62136f4bf8/quisp/rules/clauses/PurificationCountClause.cc#L6

Let me close this issue.
